name: Rebase
on:
  release:
    types:
      - publish

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
          fetch-depth: 0
      - name: Git status
        run: git status
      - name: Rebase master
        run: git rebase --onto master staging staging
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Merge staging
        run: git merge staging --ff
